### ISSUE TITLE
Tooltip layout and style

### ISSUE THREAD

**Issue by nesnoj** [empowerplan/epp-app#150]
In #110 you fixed the tooltip layout #88. However, at some places they're still truncated.
I increased the width in bf15811990e23690503065893e86df3061d0fcaf which fixed the top and bottom truncation but made it worse at left and right sides.
Could you please have a second look if this can be fixed?

Examples (with 300px width):

![image](https://github.com/empowerplan/epp-app/assets/15910173/58b5f6e5-7373-427c-8689-35ff963ee364)

![image](https://github.com/empowerplan/epp-app/assets/15910173/e6dbdaf6-90a0-469f-a54a-457204f1c419)

**Comment by bmlancien** [comment]
Alright, I'll see what I can do.

But you'll have to help me first with that one... I just pulled from dev.

`django.core.exceptions.ImproperlyConfigured: WSGI application 'config.wsgi.application' could not be loaded; Error importing module.` 

```
epp-app-django-1                | Error occurred during checks: ImproperlyConfigured("WSGI application 'config.wsgi.application' could not be loaded; Error importing module.")
epp-app-django-1                |
epp-app-django-1                |
epp-app-django-1                |  * Debugger is active!
epp-app-django-1                |  * Debugger PIN: 654-971-731
epp-app-django-1                | 172.18.0.1 - - [16/May/2024 12:06:53] "GET / HTTP/1.1" 500 -
epp-app-django-1                | Traceback (most recent call last):
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/django/core/servers/basehttp.py", line 48, in get_internal_wsgi_application
epp-app-django-1                |     return import_string(app_path)
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
epp-app-django-1                |     return cached_import(module_path, class_name)
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
epp-app-django-1                |     module = import_module(module_path)
epp-app-django-1                |   File "/venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
epp-app-django-1                |     return _bootstrap._gcd_import(name[level:], package, level)
epp-app-django-1                |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
epp-app-django-1                |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
epp-app-django-1                |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
epp-app-django-1                |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
epp-app-django-1                |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
epp-app-django-1                |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
epp-app-django-1                |   File "/app/config/wsgi.py", line 30, in <module>
epp-app-django-1                |     application = get_wsgi_application()
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
epp-app-django-1                |     return WSGIHandler()
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 118, in __init__
epp-app-django-1                |     self.load_middleware()
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 40, in load_middleware
epp-app-django-1                |     middleware = import_string(middleware_path)
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
epp-app-django-1                |     return cached_import(module_path, class_name)
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
epp-app-django-1                |     module = import_module(module_path)
epp-app-django-1                |   File "/venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
epp-app-django-1                |     return _bootstrap._gcd_import(name[level:], package, level)
epp-app-django-1                |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
epp-app-django-1                |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
epp-app-django-1                |   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
epp-app-django-1                | ModuleNotFoundError: No module named 'django_mapengine.middleware'
```

**Comment by nesnoj** [comment]
@henhuy introduced a new mapengine version in #145, have you rebuilt the docker?

**Comment by bmlancien** [comment]
Now I did, and it's working. Thanks :)
