### ISSUE TITLE
Broken layout in result toggle

### ISSUE THREAD

**Issue by nesnoj** [empowerplan/epp-app#98]
![image](https://github.com/empowerplan/epp-app/assets/15910173/6a25e541-2fda-4d91-a7cd-92df8bfc5f3a)

Please fix..

**Comment by bmlancien** [comment]
@henhuy I'm getting the following error after pulling from dev. Can you tell me what I should do?

```
epp-app-django-1                | PostgreSQL is available
epp-app-django-1                | System check identified some issues:
epp-app-django-1                |
epp-app-django-1                | WARNINGS:
epp-app-django-1                | ?: (debug_toolbar.W006) At least one DjangoTemplates TEMPLATES configuration needs to use django.template.loaders.app_directories.Loader or have APP_DIRS set to True.
epp-app-django-1                | 	HINT: Include django.template.loaders.app_directories.Loader in ["OPTIONS"]["loaders"]. Alternatively use APP_DIRS=True for at least one django.template.backends.django.DjangoTemplates backend configuration.
epp-app-django-1                |
epp-app-django-1                | Operations to perform:
epp-app-django-1                |   Apply all migrations: admin, auth, contenttypes, django_oemof, map, sessions, sites
epp-app-django-1                | Running migrations:
epp-app-django-1                |   No migrations to apply.
epp-app-django-1                | Traceback (most recent call last):
epp-app-django-1                |   File "/app/manage.py", line 32, in <module>
epp-app-django-1                |     execute_from_command_line(sys.argv)
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
epp-app-django-1                |     utility.execute()
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 416, in execute
epp-app-django-1                |     django.setup()
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
epp-app-django-1                |     apps.populate(settings.INSTALLED_APPS)
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/django/apps/registry.py", line 124, in populate
epp-app-django-1                |     app_config.ready()
epp-app-django-1                |   File "/app/digiplan/map/apps.py", line 21, in ready
epp-app-django-1                |     from digiplan.map import hooks as digiplan_hooks
epp-app-django-1                |   File "/app/digiplan/map/hooks.py", line 10, in <module>
epp-app-django-1                |     from digiplan.map import config, datapackage, forms
epp-app-django-1                |   File "/app/digiplan/map/config.py", line 121, in <module>
epp-app-django-1                |     "potentials": datapackage.get_potential_values(),
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/cache_memoize/__init__.py", line 136, in inner
epp-app-django-1                |     result = func(*args, **kwargs)
epp-app-django-1                |   File "/app/digiplan/map/datapackage.py", line 176, in get_potential_values
epp-app-django-1                |     areas = get_potential_areas()
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/cache_memoize/__init__.py", line 136, in inner
epp-app-django-1                |     result = func(*args, **kwargs)
epp-app-django-1                |   File "/app/digiplan/map/datapackage.py", line 230, in get_potential_areas
epp-app-django-1                |     data = get_data_from_sources(sources.values())
epp-app-django-1                |   File "/app/digiplan/map/datapackage.py", line 31, in get_data_from_sources
epp-app-django-1                |     dfs.append(pd.read_csv(source_path, usecols=columns))
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
epp-app-django-1                |     return _read(filepath_or_buffer, kwds)
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
epp-app-django-1                |     parser = TextFileReader(filepath_or_buffer, **kwds)
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
epp-app-django-1                |     self._engine = self._make_engine(f, self.engine)
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
epp-app-django-1                |     return mapping[engine](f, **self.options)
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 140, in __init__
epp-app-django-1                |     self._validate_usecols_names(usecols, self.orig_names)
epp-app-django-1                |   File "/venv/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 979, in _validate_usecols_names
epp-app-django-1                |     raise ValueError(
epp-app-django-1                | ValueError: Usecols do not match columns, columns expected but not found: ['roof_area_pv_potential_sqkm']
epp-app-django-1 exited with code 1
```

**Comment by nesnoj** [comment]
> epp-app-django-1                |     raise ValueError(
> epp-app-django-1                | ValueError: Usecols do not match columns, columns expected but not found: ['roof_area_pv_potential_sqkm']
> epp-app-django-1 exited with code 1

You need to replace a file in the data, I'll send you an email

**Comment by bmlancien** [comment]
> You need to replace a file in the data, I'll send you an email

It worked, thanks!

**Comment by henhuy** [comment]
Maybe we should versionize the data package and app throws an error/warning if version is outdated? What do you think?
